[package]
name = "pqbench_falcon_512"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true

[dependencies]
starknet.workspace = true
pqbench_interface.workspace = true

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true

[tool]
scarb.workspace = true
